# frozen_string_literal: true

@order_data = [
  { product_name: 'bicycle',
    seller: 'alex',
    buyer: 'Sunder',
    amount: 3_000,
    order_date: '22-01-2019' },
  { product_name: 'car',
    seller: 'meena',
    buyer: 'Sunder',
    amount: 250_000,
    order_date: '22-01-2019' },
  { product_name: 'jeans',
    seller: 'prabhu',
    buyer: 'Sunder',
    amount: 1800,
    order_date: '22-01-2019' },
  { product_name: 'shirt',
    seller: 'prabhu',
    buyer: 'Sunder',
    amount: 700,
    order_date: '22-01-2019' },
  { product_name: 'blue shirt',
    seller: 'prabhu',
    buyer: 'Sunder',
    amount: 1200,
    order_date: '22-01-2019' },
  { product_name: 't-shirt',
    seller: 'prabhu',
    buyer: 'Sunder',
    amount: 600,
    order_date: '22-01-2019' },
  { product_name: 'capri',
    seller: 'prabhu',
    buyer: 'Sunder',
    amount: 300,
    order_date: '22-01-2019' },
  { product_name: 'bike',
    seller: 'meena',
    buyer: 'Sunder',
    amount: 60_000,
    order_date: '22-01-2019' },
  { product_name: 'scooter',
    seller: 'meena',
    buyer: 'Sunder',
    amount: 25_000,
    order_date: '22-01-2019' },
  { product_name: 'maruti',
    seller: 'meena',
    buyer: 'Sunder',
    amount: 400_000,
    order_date: '22-01-2019' },
  { product_name: 'auto',
    seller: 'meena',
    buyer: 'Sunder',
    amount: 100_000,
    order_date: '22-01-2019' },
  { product_name: 'sweter',
    seller: 'prabhu',
    buyer: 'Sunder',
    amount: 1200,
    order_date: '22-01-2019' },
  { product_name: 'jacket',
    seller: 'prabhu',
    buyer: 'Sunder',
    amount: 3500,
    order_date: '22-01-2019' },
  { product_name: 'hat',
    seller: 'prabhu',
    buyer: 'Sunder',
    amount: 400,
    order_date: '22-01-2019' },
  { product_name: 'doll',
    seller: 'alex',
    buyer: 'Sunder',
    amount: 350,
    order_date: '22-01-2019' },
  { product_name: 'toy car',
    seller: 'alex',
    buyer: 'Sunder',
    amount: 250,
    order_date: '22-01-2019' },
  { product_name: 'bat',
    seller: 'alex',
    buyer: 'Sunder',
    amount: 700,
    order_date: '22-01-2019' },
  { product_name: 'ball',
    seller: 'alex',
    buyer: 'Sunder',
    amount: 20,
    order_date: '22-01-2019' },
  { product_name: 'batman',
    seller: 'alex',
    buyer: 'Sunder',
    amount: 300,
    order_date: '22-01-2019' },
  { product_name: 'barbi doll',
    seller: 'alex',
    buyer: 'Sunder',
    amount: 3_000,
    order_date: '22-01-2019' }
]
