# frozen_string_literal: true

@product_data = [
  { name: 'bicycle',
    price: 3_000,
    category: 'vehicle' },
  { name: 'car',
    price: 250_000,
    category: 'vehicle' },
  { name: 'jeans',
    price: 1800,
    category: 'clothes' },
  { name: 'shirt',
    price: 700,
    category: 'clothes' },
  { name: 'blue shirt',
    price: 1200,
    category: 'clothes' },
  { name: 't-shirt',
    price: 600,
    category: 'clothes' },
  { name: 'capri',
    price: 300,
    category: 'clothes' },
  { name: 'bike',
    price: 60_000,
    category: 'vehicle' },
  { name: 'scooter',
    price: 25_000,
    category: 'vehicle' },
  { name: 'maruti',
    price: 400_000,
    category: 'vehicle' },
  { name: 'auto',
    price: 100_000,
    category: 'vehicle' },
  { name: 'sweter',
    price: 1200,
    category: 'clothes' },
  { name: 'jacket',
    price: 3500,
    category: 'clothes' },
  { name: 'hat',
    price: 400,
    category: 'clothes' },
  { name: 'doll',
    price: 350,
    category: 'toys' },
  { name: 'toy car',
    price: 250,
    category: 'toys' },
  { name: 'bat',
    price: 700,
    category: 'toys' },
  { name: 'ball',
    price: 20,
    category: 'toys' },
  { name: 'batman',
    price: 300,
    category: 'toys' },
  { name: 'barbi doll',
    price: 3_000,
    category: 'toys' }
]
