# frozen_string_literal: true

@questions_data = [
  { quiz_name: 'cs',
    question: 'url full form ?',
    question_id: 1 },
  { quiz_name: 'cs',
    question: 'Example of dbms is ?',
    question_id: 2 },
  { quiz_name: 'cs',
    question: 'tcp full form ? ',
    question_id: 3 },
  { quiz_name: 'cs',
    question: 'ubuntu is based on a ?',
    question_id: 4 },
  { quiz_name: 'cs',
    question: 'ruby is a ?',
    question_id: 5 }
]

@choice_data = [
  { question_id: 1,
    choice_id: 1,
    choice: 'Uniform Resource Locator',
    is_right_choice: true },
  { question_id: 1,
    choice_id: 2,
    choice: 'Universal Resource Locator',
    is_right_choice: false },
  { question_id: 1,
    choice_id: 3,
    choice: 'Uniform Remote Locator',
    is_right_choice: false },
  { question_id: 1,
    choice_id: 4,
    choice: 'Uniform Resource location',
    is_right_choice: false },
  { question_id: 2,
    choice_id: 1,
    choice: 'mySql',
    is_right_choice: true },
  { question_id: 2,
    choice_id: 2,
    choice: 'windows',
    is_right_choice: false },
  { question_id: 2,
    choice_id: 3,
    choice: 'ubuntu',
    is_right_choice: false },
  { question_id: 2,
    choice_id: 4,
    choice: 'centos',
    is_right_choice: false },
  { question_id: 3,
    choice_id: 1,
    choice: 'Transmission Control Protocol',
    is_right_choice: true },
  { question_id: 3,
    choice_id: 2,
    choice: 'transfer control protocol',
    is_right_choice: false },
  { question_id: 3,
    choice_id: 3,
    choice: 'transfer console protocol',
    is_right_choice: false },
  { question_id: 3,
    choice_id: 4,
    choice: 'transfer control public',
    is_right_choice: false },
  { question_id: 4,
    choice_id: 1,
    choice: 'debian',
    is_right_choice: true },
  { question_id: 4,
    choice_id: 2,
    choice: 'windows',
    is_right_choice: false },
  { question_id: 4,
    choice_id: 3,
    choice: 'mac-os',
    is_right_choice: false },
  { question_id: 4,
    choice_id: 4,
    choice: 'nothing',
    is_right_choice: false },
  { question_id: 5,
    choice_id: 1,
    choice: 'programing language',
    is_right_choice: true },
  { question_id: 5,
    choice_id: 2,
    choice: 'gem',
    is_right_choice: false },
  { question_id: 5,
    choice_id: 3,
    choice: 'object',
    is_right_choice: false },
  { question_id: 5,
    choice_id: 4,
    choice: 'nothing',
    is_right_choice: false }
]

@quiz_data = [
  { name: 'cs' },
  { name: 'it' },
  { name: 'ec' },
  { name: 'ee' },
  { name: 'me' }
]
